# Generated by Django 4.2.16 on 2026-07-03 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分類名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '分類',
                'verbose_name_plural': '分類',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='標籤名稱')),
            ],
            options={
                'verbose_name': '標籤',
                'verbose_name_plural': '標籤',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='題目標題')),
                ('content', models.TextField(verbose_name='題目內容')),
                ('option_a', models.TextField(verbose_name='選項 A')),
                ('option_b', models.TextField(verbose_name='選項 B')),
                ('option_c', models.TextField(verbose_name='選項 C')),
                ('option_d', models.TextField(verbose_name='選項 D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='正確答案')),
                ('hint', models.TextField(blank=True, verbose_name='提示')),
                ('solution_idea', models.TextField(blank=True, verbose_name='解題思路')),
                ('explanation', models.TextField(blank=True, verbose_name='詳細解說')),
                ('difficulty', models.CharField(choices=[('easy', '簡單'), ('medium', '中等'), ('hard', '困難')], default='medium', max_length=10, verbose_name='難度')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年份')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.category', verbose_name='分類')),
                ('tags', models.ManyToManyField(blank=True, to='questions.tag', verbose_name='標籤')),
            ],
            options={
                'verbose_name': '題目',
                'verbose_name_plural': '題目',
                'ordering': ['-created_at'],
            },
        ),
    ]
