services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-apcs_db}
      POSTGRES_USER: ${POSTGRES_USER:-apcs_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apcs_password}
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8443:8000"
    env_file:
      - .env
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-adminpassword}
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume:
