# Generated by Django 4.2.16 on 2026-07-03 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班級名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('class_code', models.CharField(max_length=10, unique=True, verbose_name='班級代號')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('allow_join', models.BooleanField(default=True, verbose_name='允許加入')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_classes', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '班級',
                'verbose_name_plural': '班級',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassExamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('is_required', models.BooleanField(default=True, verbose_name='必做')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='指派時間')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exams', to=settings.AUTH_USER_MODEL)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='classes.classroom')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='exams.exam')),
            ],
            options={
                'verbose_name': '班級考卷指派',
                'verbose_name_plural': '班級考卷指派',
                'ordering': ['-created_at'],
                'unique_together': {('class_room', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '班級成員',
                'verbose_name_plural': '班級成員',
                'ordering': ['joined_at'],
                'unique_together': {('class_room', 'user')},
            },
        ),
    ]
