# Generated by Django 4.2.16 on 2026-07-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_oauth_enabled', models.BooleanField(default=False, verbose_name='啟用 Google 帳號登入')),
                ('google_oauth_client_id', models.CharField(blank=True, max_length=300, verbose_name='Google Client ID')),
                ('google_oauth_client_secret', models.CharField(blank=True, max_length=300, verbose_name='Google Client Secret')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='上次更新')),
            ],
            options={
                'verbose_name': '平台設定',
                'verbose_name_plural': '平台設定',
            },
        ),
    ]
