# Generated by Django 4.2.16 on 2026-07-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(blank=True, default='幫助學生準備 APCS 考試，提升程式設計能力', max_length=200, verbose_name='頁尾文字'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_color',
            field=models.CharField(default='#212529', max_length=7, verbose_name='首頁封面顏色'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_color',
            field=models.CharField(default='#212529', max_length=7, verbose_name='導覽列顏色'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#0d6efd', max_length=7, verbose_name='主題色彩（按鈕/連結）'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_icon',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='網站圖示（Icon）'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='APCS 練習平台', max_length=100, verbose_name='網站名稱'),
        ),
    ]
