# Generated by Django 4.2.16 on 2026-07-03 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='考卷名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='考卷代號')),
                ('time_limit', models.IntegerField(default=30, help_text='分鐘', verbose_name='時間限制（分鐘）')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('show_score', models.BooleanField(default=True, verbose_name='顯示分數')),
                ('show_explanation', models.BooleanField(default=False, verbose_name='顯示詳解')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '考卷',
                'verbose_name_plural': '考卷',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='開始時間')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='交卷時間')),
                ('score', models.IntegerField(default=0, verbose_name='分數')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='已交卷')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '考試紀錄',
                'verbose_name_plural': '考試紀錄',
                'ordering': ['-started_at'],
                'unique_together': {('exam', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='順序')),
                ('score', models.IntegerField(default=5, verbose_name='分數')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_exams', to='questions.question')),
            ],
            options={
                'verbose_name': '考卷題目',
                'verbose_name_plural': '考卷題目',
                'ordering': ['order'],
                'unique_together': {('exam', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, max_length=1, verbose_name='選擇的答案')),
                ('confidence', models.CharField(blank=True, max_length=10, verbose_name='信心程度')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否答對')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='作答時間')),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examsession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'verbose_name': '考試答案',
                'verbose_name_plural': '考試答案',
                'unique_together': {('exam_session', 'question')},
            },
        ),
    ]
