# Generated by Django 4.2.16 on 2026-07-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='anti_cheat',
            field=models.BooleanField(default=False, verbose_name='啟用防作弊（切換視窗偵測）'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='cheat_count',
            field=models.IntegerField(default=0, verbose_name='切換視窗次數'),
        ),
    ]
