# Generated by Django 4.2.16 on 2026-08-08 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_anti_cheat_examsession_cheat_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='score',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='分數'),
        ),
    ]
