# Generated by Django 4.2.16 on 2026-08-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_examquestion_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='official_ui',
            field=models.BooleanField(default=False, help_text='開啟後，學生作答畫面會切換成類似 APCS 程式識讀檢測的單題單頁介面（無網站選單、頂部題號＋倒數、底部作答列）。', verbose_name='模擬 APCS 正式考試介面'),
        ),
    ]
