# Generated by Django 4.2.16 on 2026-07-03 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=1, verbose_name='選擇的答案')),
                ('confidence', models.CharField(blank=True, choices=[('sure', '很確定'), ('unsure', '不太確定'), ('guess', '猜的')], max_length=10, verbose_name='信心程度')),
                ('is_correct', models.BooleanField(verbose_name='是否答對')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='作答時間')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_records', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '練習紀錄',
                'verbose_name_plural': '練習紀錄',
                'ordering': ['-answered_at'],
            },
        ),
        migrations.CreateModel(
            name='WrongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_count', models.IntegerField(default=1, verbose_name='錯誤次數')),
                ('review_count', models.IntegerField(default=0, verbose_name='複習次數（連續答對）')),
                ('next_review_at', models.DateTimeField(blank=True, null=True, verbose_name='下次複習時間')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已解決')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_by', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '錯題',
                'verbose_name_plural': '錯題',
                'ordering': ['next_review_at'],
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='QuestionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='筆記內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '筆記',
                'verbose_name_plural': '筆記',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏時間')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '收藏題目',
                'verbose_name_plural': '收藏題目',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
